project:
  type: website
  output-dir: docs

website:
  title: "Alex Kaizer"
  search: true
  navbar:
    pinned: true
    left:
      - text: "Research"
        href: https://www.alexkaizer.com/research.html
      - text: "Publications"
        href: https://www.alexkaizer.com/publications.html
      - text: "Teaching"
        menu:
          - text: "Overview"
            href: https://www.alexkaizer.com/teaching.html
          - text: "BIOS 6618"
            href: https://www.alexkaizer.com/bios_6618
          - text: "BIOS 6611"
            href: https://www.alexkaizer.com/bios_6611
          - text: "BERD Study Design Short Course"
            href: https://www.alexkaizer.com/study_design_berd.html
          - text: "WNAR Adaptive and Bayesian Clinical Trial Design Short Course"
            href: https://www.alexkaizer.com/adaptivetrials_sc 
      - text: "BIOS 6611"
        menu:
          - text: "Home"
            href: index.html
          - text: "Materials"
            href: bios_6611_materials
          - text: "Journal of BIOS 6611"
            href: journal_of_bios_6611
    right:
      - icon: envelope
        href: mailto:alex.kaizer@cuanschutz.edu
      - text: "{{< ai google-scholar size=large >}}" # TERMINAL PROMPT: quarto install extension schochastics/academicons
        href: https://scholar.google.com/citations?user=ICpH74EAAAAJ&hl=en
      - icon: github
        href: http://github.com/alexbiostats
      - text: "{{< ai cv size=large >}}" # TERMINAL PROMPT: quarto install extension schochastics/academicons
        href: https://www.alexkaizer.com/files/Alex_CV.pdf
      - icon: linkedin
        href: https://www.linkedin.com/in/alex-kaizer/

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    
include-in-header:
  - header.html
  - header-tracker.html